require('global')
require('reload-config')
require('sync')
require('keyboard')
require('other')
local wifi = require('wifi')
local proxy = require('proxy')
local nas = require('nas')

wifi.onAtHome(function()
  proxy.closeProxy()
  nas.mountNAS()
end)

wifi.onAtWork(function()
  proxy.closeProxy()
  nas.unmountNAS()
end)

wifi.onElsewhere(function()
  proxy.openProxy()
  nas.unmountNAS()
end)

hs.alert.show('Hammerspoon config loaded')
