require('global')
require('reload-config')
require('sync')
require('keyboard')
require('other')
local wifi = require('wifi')
local vpn = require('vpn')
local nas = require('nas')

wifi.onAtHome(function()
  vpn.closeVPN()
  nas.mountNAS()
end)

wifi.onAtWork(function()
  vpn.closeVPN()
  nas.unmountNAS()
end)

wifi.onElsewhere(function()
  vpn.openVPN()
  nas.unmountNAS()
end)

hs.alert.show('Hammerspoon config loaded')
